# Generated by Django 3.1.7 on 2021-02-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=255)),
                ('answer', models.FileField(upload_to='answer')),
            ],
        ),
    ]
