# Generated by Django 3.1.7 on 2021-02-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csi_app', '0002_student_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_answer',
            name='code',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
